### ISSUE TITLE
Sharada ekam

### ISSUE THREAD

**Issue by wujastyk** [chchch/PedanticIndic#1]
Dear Charles, Deepro needs to be able to use Sharada ekam 𑇚  and siddham 𑇛, in oXygenxml and Saktumiva.  In looking at this issue, I realized that Pedantic Indic doesn't have the Roman glyphs that Sanskrit 2003 has.  What was the reason for removing them?  It limits the usablility of the font, at least in oXygen and other editors that can't silently switch font according to Unicode block.

Meanwhile, could you provide a way to encode Sharada ekam and siddham in XML and Saktumiva?

Best,
Dominik

**Comment by chchch** [comment]
Hello,

I've added two new definitions to the definitions.xml file so that you can do `<g ref="#sarada-siddhi"/>` and `<g ref="#sarada-ekam"/>`.

For the Devanāgarī font, which weight are you using? I think I got rid of them so I wouldn't have to bother with making different weights for the Latin glyphs as well. Maybe I can just put them back for the default ("medium") weight?

**Comment by wujastyk** [comment]
Perfect, thank you Charles!

Medium weight Roman would definitely help.  This isn't for typesetting or
anything posh, but very helpful just for screen display in an editor.  The
only downside I can think of is that the font file will be a bit bigger.
But we should all be able to survive that.

I thought Noto would work, but it doesn't have Sharada yet.  Noto Sharada
is good, but excludes Latin.  GNU Unifont is unusable for daily work, and
also doesn't have Śāradā anyway

Best,
Dominik

**Comment by chchch** [comment]
PS I added the Latin characters back to Pedantic Devanagari medium.

**Comment by wujastyk** [comment]
Thank you!
